name: ghl-app
description: GHL Integration App - Integração bidirecional GHL ↔ Evolution API

services:
  - name: ghl-app
    type: app
    source:
      type: git
      url: https://github.com/hayttle/ghl-app.git
      branch: main
    build:
      type: node
      nodeVersion: 18
      buildCommand: npm run build
      startCommand: npm start
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: 3000
    ports:
      - 3000
    volumes:
      - name: ghl-app-data
        mountPath: /app/data
    healthCheck:
      path: /health
      port: 3000
      interval: 30s
      timeout: 10s
      retries: 3

databases:
  - name: ghl-postgres
    type: postgresql
    version: 15
    env:
      - name: POSTGRES_DB
        value: ghl_integration
      - name: POSTGRES_USER
        value: ghl_user
      - name: POSTGRES_PASSWORD
        value: ghl_password

volumes:
  - name: ghl-app-data
    size: 1Gi
